site_name: Python основи
site_url: https://ekidscoding.github.io/python0/
theme:
  favicon: assets/favicon.ico
  logo: assets/logo.png
  name: material
  language: uk
  font:
    text: Source Sans 3
    code: Source Code Pro
  features:
    - navigation.top
    - content.code.copy
    - navigation.footer

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg